-- ============================================================
-- SCRIPT DE INICIALIZAÇÃO DO BANCO DE DADOS SUPABASE
-- Execute este script no SQL Editor do seu projeto Supabase.
-- ============================================================

-- ── 1. TABELA: profiles (Perfis de Usuários) ─────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer' CONSTRAINT chk_role CHECK (role IN ('admin', 'manager', 'operator', 'viewer')),
    avatar_url TEXT,
    store_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 2. TABELA: products (Produtos) ───────────────────────────
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    code TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    min_stock INTEGER NOT NULL DEFAULT 0,
    price NUMERIC NOT NULL CONSTRAINT chk_price CHECK (price >= 0),
    status TEXT NOT NULL DEFAULT 'Ativo' CONSTRAINT chk_status CHECK (status IN ('Ativo', 'Inativo')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 3. TABELA: sales (Vendas) ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL, -- Armazena a data no formato ISO YYYY-MM-DD
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL CONSTRAINT chk_quantity CHECK (quantity > 0),
    total NUMERIC NOT NULL CONSTRAINT chk_total CHECK (total >= 0),
    customer TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 4. TABELA: inventory_adjustments (Ajustes de Estoque) ────
CREATE TABLE IF NOT EXISTS public.inventory_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    quantity_before INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    reason TEXT NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 5. VIEW: low_stock_products (Produtos com Baixo Estoque) ─
CREATE OR REPLACE VIEW public.low_stock_products AS
SELECT * FROM public.products
WHERE stock <= min_stock AND status = 'Ativo';

-- ── 6. FUNÇÃO RPC: get_inventory_value (Valor Total em Estoque)
CREATE OR REPLACE FUNCTION public.get_inventory_value()
RETURNS NUMERIC AS $$
    SELECT COALESCE(SUM(stock * price), 0) FROM public.products WHERE status = 'Ativo';
$$ LANGUAGE SQL SECURITY DEFINER;

-- ── 7. FUNÇÃO RPC: restock_product (Reabastecer Estoque) ─────
CREATE OR REPLACE FUNCTION public.restock_product(product_id BIGINT, quantity INTEGER)
RETURNS VOID AS $$
BEGIN
    IF quantity <= 0 THEN
        RAISE EXCEPTION 'A quantidade deve ser maior que zero';
    END IF;

    UPDATE public.products
    SET stock = stock + quantity,
        updated_at = now()
    WHERE id = product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── 8. GATILHO (TRIGGER): Criação automática de Perfil ────────
-- Cria um perfil na tabela public.profiles sempre que um novo usuário
-- é criado no Auth do Supabase.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (id, name, email, role, store_name)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'name', 'Novo Usuário'),
        new.email,
        'admin', -- Configura o primeiro usuário/todos como admin por padrão para testes
        'Minha Loja'
    );
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Remove o gatilho se ele já existir para evitar duplicidade
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── 9. POLÍTICAS DE SEGURANÇA (RLS - Row Level Security) ──────
-- Habilita RLS em todas as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_adjustments ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas se existirem
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.profiles;
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.products;
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.sales;
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.inventory_adjustments;

-- Cria novas políticas que permitem leitura/escrita total para usuários autenticados
CREATE POLICY "Allow all actions for authenticated users" ON public.profiles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.products FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.sales FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.inventory_adjustments FOR ALL TO authenticated USING (true) WITH CHECK (true);
