-- ============================================================
-- SCRIPT DE INICIALIZAÇÃO DO BANCO DE DADOS SUPABASE
-- Execute este script no SQL Editor do seu projeto Supabase.
-- v1.1 — Inclui owner_id, RLS isolada por usuário e RPC atômica
-- ============================================================

-- ── 1. TABELA: profiles (Perfis de Usuários) ─────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer' CONSTRAINT chk_role CHECK (role IN ('admin', 'manager', 'operator', 'viewer')),
    avatar_url TEXT,
    store_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 2. TABELA: products (Produtos) ───────────────────────────
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    code TEXT NOT NULL,
    category TEXT NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    min_stock INTEGER NOT NULL DEFAULT 0,
    price NUMERIC NOT NULL CONSTRAINT chk_price CHECK (price >= 0),
    status TEXT NOT NULL DEFAULT 'Ativo' CONSTRAINT chk_status CHECK (status IN ('Ativo', 'Inativo')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Índice único por código dentro da mesma loja (owner)
CREATE UNIQUE INDEX IF NOT EXISTS products_owner_code_idx ON public.products(owner_id, code);

-- ── 3. TABELA: sales (Vendas) ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL CONSTRAINT chk_quantity CHECK (quantity > 0),
    total NUMERIC NOT NULL CONSTRAINT chk_total CHECK (total >= 0),
    customer TEXT NOT NULL DEFAULT 'Cliente',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 4. TABELA: inventory_adjustments (Ajustes de Estoque) ────
CREATE TABLE IF NOT EXISTS public.inventory_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL DEFAULT '',
    quantity_before INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    reason TEXT NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ── 5. VIEW: low_stock_products (Produtos com Baixo Estoque) ─
CREATE OR REPLACE VIEW public.low_stock_products AS
SELECT * FROM public.products
WHERE stock <= min_stock AND status = 'Ativo';

-- ── 6. FUNÇÃO: set_owner_id (Trigger para preencher owner_id) ─
CREATE OR REPLACE FUNCTION public.set_owner_id()
RETURNS TRIGGER AS $$
BEGIN
  NEW.owner_id := auth.uid();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Triggers de owner_id
DROP TRIGGER IF EXISTS set_products_owner ON public.products;
CREATE TRIGGER set_products_owner
  BEFORE INSERT ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_owner_id();

DROP TRIGGER IF EXISTS set_sales_owner ON public.sales;
CREATE TRIGGER set_sales_owner
  BEFORE INSERT ON public.sales
  FOR EACH ROW EXECUTE FUNCTION public.set_owner_id();

DROP TRIGGER IF EXISTS set_adjustments_owner ON public.inventory_adjustments;
CREATE TRIGGER set_adjustments_owner
  BEFORE INSERT ON public.inventory_adjustments
  FOR EACH ROW EXECUTE FUNCTION public.set_owner_id();

-- ── 7. FUNÇÃO RPC: get_inventory_value ───────────────────────
CREATE OR REPLACE FUNCTION public.get_inventory_value()
RETURNS NUMERIC AS $$
  SELECT COALESCE(SUM(stock * price), 0)
  FROM public.products
  WHERE status = 'Ativo' AND owner_id = auth.uid();
$$ LANGUAGE SQL SECURITY DEFINER;

-- ── 8. FUNÇÃO RPC: restock_product ───────────────────────────
CREATE OR REPLACE FUNCTION public.restock_product(p_product_id BIGINT, p_quantity INTEGER)
RETURNS VOID AS $$
BEGIN
  IF p_quantity <= 0 THEN
    RAISE EXCEPTION 'A quantidade deve ser maior que zero';
  END IF;

  UPDATE public.products
  SET stock = stock + p_quantity,
      updated_at = now()
  WHERE id = p_product_id AND owner_id = auth.uid();

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Produto não encontrado ou sem permissão';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── 9. FUNÇÃO RPC: create_sale_and_deduct_stock (Atômica) ────
-- Cria a venda e deduz o estoque em uma única transação.
-- Lança exceção se o estoque for insuficiente.
CREATE OR REPLACE FUNCTION public.create_sale_and_deduct_stock(
  p_product_id BIGINT,
  p_product_name TEXT,
  p_quantity INTEGER,
  p_total NUMERIC,
  p_customer TEXT,
  p_date TEXT
)
RETURNS TABLE(
  sale_id BIGINT,
  new_stock INTEGER
) AS $$
DECLARE
  v_current_stock INTEGER;
  v_sale_id BIGINT;
  v_new_stock INTEGER;
BEGIN
  -- Bloquear a linha do produto para evitar race conditions
  SELECT stock INTO v_current_stock
  FROM public.products
  WHERE id = p_product_id AND owner_id = auth.uid()
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Produto não encontrado ou sem permissão';
  END IF;

  IF v_current_stock < p_quantity THEN
    RAISE EXCEPTION 'Estoque insuficiente. Disponível: %, solicitado: %',
      v_current_stock, p_quantity;
  END IF;

  -- Inserir a venda
  INSERT INTO public.sales (owner_id, date, product_id, product_name, quantity, total, customer)
  VALUES (auth.uid(), p_date, p_product_id, p_product_name, p_quantity, p_total, p_customer)
  RETURNING id INTO v_sale_id;

  -- Decrementar o estoque
  UPDATE public.products
  SET stock = stock - p_quantity,
      updated_at = now()
  WHERE id = p_product_id AND owner_id = auth.uid()
  RETURNING stock INTO v_new_stock;

  RETURN QUERY SELECT v_sale_id, v_new_stock;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── 10. TRIGGER: Criação automática de Perfil ────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role, store_name)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    'admin',
    'Minha Loja'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── 11. RLS — Row Level Security isolada por owner_id ────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_adjustments ENABLE ROW LEVEL SECURITY;

-- Remover políticas antigas
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.profiles;
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.products;
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.sales;
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.inventory_adjustments;
DROP POLICY IF EXISTS "owner_access" ON public.products;
DROP POLICY IF EXISTS "owner_access" ON public.sales;
DROP POLICY IF EXISTS "owner_access" ON public.inventory_adjustments;

-- Profiles: cada usuário vê/edita apenas o próprio perfil
CREATE POLICY "profiles_owner" ON public.profiles
  FOR ALL TO authenticated
  USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Products: isolado por owner_id
CREATE POLICY "products_owner" ON public.products
  FOR ALL TO authenticated
  USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

-- Sales: isolado por owner_id
CREATE POLICY "sales_owner" ON public.sales
  FOR ALL TO authenticated
  USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

-- Inventory adjustments: isolado por owner_id
CREATE POLICY "adjustments_owner" ON public.inventory_adjustments
  FOR ALL TO authenticated
  USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
